services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dina
      POSTGRES_PASSWORD: dina
      POSTGRES_DB: dina
    ports:
      - "5432:5432"
    volumes:
      - dina_pg:/var/lib/postgresql/data

volumes:
  dina_pg:
